// <auto-generated />
using System;
using ClimateTrackr_Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClimateTrackr_Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ClimateTrackr_Server.Models.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ActionMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("History");
                });

            modelBuilder.Entity("ClimateTrackr_Server.Models.NotificationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("ClimateTrackr_Server.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("PdfContent")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("ClimateTrackr_Server.Models.RoomConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Window")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RoomConfigs");
                });

            modelBuilder.Entity("ClimateTrackr_Server.Models.Smtp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AuthOption")
                        .HasColumnType("int");

                    b.Property<int>("ConnSecurity")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SmtpEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SmtpHelo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("int");

                    b.Property<string>("SmtpServer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SmtpSettings");
                });

            modelBuilder.Entity("ClimateTrackr_Server.Models.TempAndHum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Humidity")
                        .HasColumnType("double");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Temperature")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("TempAndHums");
                });

            modelBuilder.Entity("ClimateTrackr_Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EnableNotifications")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Usertype")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ClimateTrackr_Server.Models.UserRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("NotificationSettingsId")
                        .HasColumnType("int");

                    b.Property<int>("RoomConfigId")
                        .HasColumnType("int");

                    b.Property<string>("RoomName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NotificationSettingsId");

                    b.HasIndex("RoomConfigId");

                    b.ToTable("UserRooms");
                });

            modelBuilder.Entity("ClimateTrackr_Server.Models.NotificationSettings", b =>
                {
                    b.HasOne("ClimateTrackr_Server.Models.User", "User")
                        .WithOne("NotificationSettings")
                        .HasForeignKey("ClimateTrackr_Server.Models.NotificationSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClimateTrackr_Server.Models.UserRoom", b =>
                {
                    b.HasOne("ClimateTrackr_Server.Models.NotificationSettings", null)
                        .WithMany("SelectedRoomNames")
                        .HasForeignKey("NotificationSettingsId");

                    b.HasOne("ClimateTrackr_Server.Models.RoomConfig", null)
                        .WithMany("UserRoomConfigs")
                        .HasForeignKey("RoomConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClimateTrackr_Server.Models.NotificationSettings", b =>
                {
                    b.Navigation("SelectedRoomNames");
                });

            modelBuilder.Entity("ClimateTrackr_Server.Models.RoomConfig", b =>
                {
                    b.Navigation("UserRoomConfigs");
                });

            modelBuilder.Entity("ClimateTrackr_Server.Models.User", b =>
                {
                    b.Navigation("NotificationSettings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
